---
hosted: aws
rt: true

postfix_additional_trusted_networks: "172.17.0.0/16"
postfix_relay_domains:
  - rt.okfn.org
postfix_sender_access: |
  tenderapp.com REJECT
  pm.mtasv.net REJECT
  rackspacecloud.com REJECT

postfix_smtpd_recipient_restrictions:
  - check_policy_service inet:127.0.0.1:10023
  - reject_rbl_client bl.spamcop.net
  - reject_rbl_client zen.spamhaus.org
  - reject_rbl_client dnsbl-1.uceprotect.net

# nginx config
sites_enabled
  - rt.okfn.org
