
- name: Add icinga PPAs
  apt_repository: repo='ppa:formorer/icinga'

- name: Add icinga-web PPA
  apt_repository: repo='ppa:formorer/icinga-web'

- name: Install icinga packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - icinga2
  - icinga2-bin
  - icinga2-common
  - icingaweb2
  - icingaweb2-module-doc
  - icinga2-ido-mysql
  - spawn-fcgi

- name: Install icinga extra software
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - mysql-server
  - python-mysqldb

# Copy config files over if needed

# The handler to import the schema is only called on DB creation.
- name: Create mysql database
  mysql_db: name=icinga state=present
  notify: import icinga schema

- name: Create user for mysql database
  mysql_user: name=icinga password={{ icinga_db_password }} priv=icinga.*:ALL state=present

- name: Enable external commands from the web interface
  command: icinga2 feature enable command

- name: Enable ido-mysql in icinga2
  command: icinga2 feature enable ido-mysql
  notify: restart icinga2
# Setup the web console
# Might be as simple as adding a nginx role
