# Setup RT pre-reqs

# Install RT


# Configure RT

- name: configure rt server
  copy: src=RT_SiteConfig.pm dest=/data/rt/rt_conf/ owner=root group=www-data mode=0640
  notify: restart rt

# Configure Postfix


# Configure Procmail

- name: configure procmail
  copy: src=procmailrc.rt dest=/data/rt/rt_postfix/procmailrc.rt owner=root group=root mode=0644
