# Setup RT pre-reqs

- name: Install RT pre-reqs through apt-get
  apt: pkg={{ item }} state=installed
  with_items:
  - build-essential 
  - postgresql-client 
  - apache2 
  - mailutils 
  - openssl 
  - libyaml-perl 
  - libyaml-appconfig-perl 
  - libssl-dev 
  - libexpat1-dev
#  - libapache2-mod-fastcgi

# Install RT
 
#- name: create RT install directory
#  file: state=directory path=/opt/rt4

- name: get latest RT release
  get_url: url=https://download.bestpractical.com/pub/rt/release/rt-4.2.9.tar.gz dest=/opt/

- name: extract RT 
  unarchive: src=/opt/rt-4.2.9.tar.gz dest=/opt/ copy=no

- name: copy rt dir to rt4 dir
  command: mv /opt/rt-4.2.9 /opt/rt4

- name: configure RT install
  command: ./configure
  args:  
    chdir: /opt/rt4
 
#- name: make testdeps
 # command: make testdeps
  #args:
   # chdir: /opt/rt4

- name: configure cpan
  command: /usr/bin/perl -MCPAN -e shell
  args: 
    chdir: /opt/rt4
#-# name: make fixdeps

#- name: make install

# We already have a DB, so no need to initialise the database

# Configure RT

#- name: configure rt server
 # copy: src=RT_SiteConfig.pm dest=/data/rt/rt_conf/ owner=root group=www-data mode=0640
  #notify: restart rt

# Configure Postfix


# Configure Procmail

#- name: configure procmail
 # copy: src=procmailrc.rt dest=/data/rt/rt_postfix/procmailrc.rt owner=root group=root mode=0644
